version: "2"
services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpw"
      MYSQL_DATABASE: "thenewdb"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpass"
    volumes:
      - "/F_DRIVE/Internal Projects/Docker-LAMP/config/mysql.conf.d/custom-mysql.cnf:/etc/mysql/conf.d/custom-mysql.cnf"
      - "/F_DRIVE/Internal Projects/Docker-LAMP/data/mysql:/var/lib/mysql"

  server:
    build:
      context: .
      dockerfile: ./build/php-apache.Dockerfile
    image: alexk/apachephp:1.00
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/F_DRIVE/Internal Projects/Docker-LAMP/app:/var/www/html"
      - "/F_DRIVE/Internal Projects/Docker-LAMP/config/000-default.conf:/etc/apache2/sites-available/000-default.conf"
      - "/F_DRIVE/Internal Projects/Docker-LAMP/config/custom-php.ini:/etc/php/7.1/apache2/conf.d/custom-php.ini"
      - "/F_DRIVE/Internal Projects/Docker-LAMP/logs:/var/log/apache2"
    links:
      - db
      - mail

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - "8080:80"
    links:
      - db

  mail:
    restart: always
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"